name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: peer npm
        run: npm config set legacy-peer-deps true
      - name: install modules
        run: npm install
      - name: build production project 
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: unit testing
        run: npm run test:unit
      - name: start storybook
        run: npm run storybook
      - name: screenshot testing
        run: npm run test:ui



